### ISSUE TITLE
SEO tab input fields do not render in Wagtail 5

### ISSUE THREAD

**Issue by isolationism** [Frojd/wagtail-meta-preview#9]
The input tags for the SEO tab's fields don't render visibly, or in the DOM, in Wagtail 5. Because of the nature and location of the problem, the error passes silently.

https://github.com/Frojd/wagtail-meta-preview/blob/cd072d3ae978d87298670736a8cae81782309eaf/wagtail_meta_preview/templates/wagtail_meta_preview/preview_panel.html#L22

The used `render_as_field` method was deprecated in Wagtail 3, and removed in Wagtail 5, as explained in the docs:

https://docs.wagtail.org/en/latest/releases/5.0.html#removal-of-deprecated-features

Workaround is to copy the `wagtail_meta_preview/preview_panel.html` template into my own project, eplacing line 22 with:

```html
<!-- ... -->
<li class="{{ child.classes|join:" " }}">
    {% comment %}
        Override block below for Wagtail 5 compatibility
    {% endcomment %}
    {{ child.bound_field.label }}
    <div class="w-field__wrapper" style="padding-top: 0.5rem">
        {{ child.bound_field }}
    </div>
</li>
<!-- ... -->
```

**Comment by marteinn** [comment]
Hi @isolationism and thanks for reporting this issue along with a suggested solution. I can confirm this error and will include a fix, based on your code above, in the next release. Will keep this open until this issue is solved.

**Comment by marteinn** [comment]
This issue is solved in https://github.com/Frojd/wagtail-meta-preview/releases/tag/v3.0.0

**Comment by isolationism** [comment]
Thank you @marteinn — grateful for your stewardship.
